language: elixir

elixir:
  - 1.7

otp_release:
  - 21.2

env:
  - MIX_ENV=test

script:
  - mix compile --warnings-as-errors 
  - mix credo
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report